AplicacionDeBiblioteca.UI/Models/ContextoDeBaseDeDatos.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AplicacionDeBiblioteca.UI.Models
{
    public class ContextoDeBaseDeDatos : DbContext
    {

        public DbSet<Libro> Libros { get; set; }

        public ContextoDeBaseDeDatos(DbContextOptions<ContextoDeBaseDeDatos> opciones) : base(opciones)
        {

        }
    }
}

AplicacionDeBiblioteca.UI/Models/ErrorViewModel.cs
using System;

namespace AplicacionDeBiblioteca.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AplicacionDeBiblioteca.UI/Models/IRepositorioDeLibros.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AplicacionDeBiblioteca.UI.Models
{
    public interface IRepositorioDeLibros
    {
        List<Libro> ObtenerTodos();

        void Agregar(Models.Libro libro);
    }
}

AplicacionDeBiblioteca.UI/Models/Libro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlTypes;
using System.Linq;
using System.Threading.Tasks;

namespace AplicacionDeBiblioteca.UI.Models
{
    public class Libro
    {
        public String Nombre { get; set; }
        public String Autor { get; set; }

        [Display(Name = "Fecha De Publicación")]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public DateTime FechaDePublicacion { get; set; }
        
        [Range(0,1,ErrorMessage ="El libro debe tener estado disponible (1)")]
        public int Estado { get; set; }
        public int ID { get; set; }    
    }
}

AplicacionDeBiblioteca.UI/Models/MockRepositorioDeLibros.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AplicacionDeBiblioteca.UI.Models
{
    public class MockRepositorioDeLibros : IRepositorioDeLibros
    {
        public void Agregar(Libro libro)
        {
            throw new NotImplementedException();
        }

        public List<Libro> ObtenerTodos()
        {
            List<Libro> laListaDeLibros = new List<Libro>();
            /*
            laListaDeLibros.Add(new Libro { Nombre = "Trafalgar", Autor = "Benito Perez Galdos", FechaDePublicacion = "1873", Estado = "Disponible"});
            laListaDeLibros.Add(new Libro { Nombre = "Historia general de los robos y asesinatos de los más famosos piratas", Autor = "Capitán Charles Johnson", FechaDePublicacion = "14/05/1724", Estado = "Prestado" });
            laListaDeLibros.Add(new Libro { Nombre = "Bajo bandera negra: La vida entre piratas", Autor = "David Cordingly", FechaDePublicacion = "1995", Estado = "Prestado"});
            laListaDeLibros.Add(new Libro { Nombre = "La república de los piratas", Autor = "Colin Woodard", FechaDePublicacion = 01 / 05 / 2007, Estado = "Disponible" });
            laListaDeLibros.Add(new Libro { Nombre = "Kama-Sutra", Autor = "Vatsiaiana", FechaDePublicacion = "550 d.C", Estado = "Disponible"});
            */
            return laListaDeLibros;
        }
    }
}

AplicacionDeBiblioteca.UI/Models/RepositorioDeLibros.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AplicacionDeBiblioteca.UI.Models
{
    public class RepositorioDeLibros : IRepositorioDeLibros
    {
        private ContextoDeBaseDeDatos ElContextoDeBaseDeDatos;

        public RepositorioDeLibros(ContextoDeBaseDeDatos contexto)
        {
            ElContextoDeBaseDeDatos = contexto;
        }

        public void Agregar(Libro libro)
        {
            ElContextoDeBaseDeDatos.Libros.Add(libro);
            ElContextoDeBaseDeDatos.SaveChanges();
        }

        public List<Libro> ObtenerTodos()
        {
            return ElContextoDeBaseDeDatos.Libros.ToList();
        }
    }
}

AplicacionDeBiblioteca.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AplicacionDeBiblioteca.UI.Models;

namespace AplicacionDeBiblioteca.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AplicacionDeBiblioteca.UI/Controllers/LibrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AplicacionDeBiblioteca.UI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AplicacionDeBiblioteca.UI.Controllers
{
    public class LibrosController : Controller
    {

        private IRepositorioDeLibros Repositorio;

        public LibrosController(IRepositorioDeLibros repositorioDelConstructor)
        {
            Repositorio = repositorioDelConstructor;
        }

        // GET: Libros
        public ActionResult Listar()
        {
            List<Libro> laLista;
            laLista = Repositorio.ObtenerTodos();
            return View(laLista);
        }

        // GET: Libros/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Libros/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Libros/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Libro libro)
        {
            if (ModelState.IsValid)
            {
                Repositorio.Agregar(libro);
                return RedirectToAction("Listar");
            }
                return View();
        }

        // GET: Libros/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Libros/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Libros/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Libros/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AplicacionDeBiblioteca.UI/Views/Home/Index.cshtml
@{
    ViewData["Aplicación de Biblioteca"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AplicacionDeBiblioteca.UI/Views/Libros/Create.cshtml
@model AplicacionDeBiblioteca.UI.Models.Libro

@{
    ViewData["Title"] = "Nuevo Libro";
}

<h1>Nuevo Libro</h1>

<h4>Libro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDePublicacion" class="control-label"></label>
                <input type="date" asp-for="FechaDePublicacion" class="form-control" />
                <span asp-validation-for="FechaDePublicacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Listar">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AplicacionDeBiblioteca.UI/Views/Libros/Listar.cshtml
 @model IEnumerable<AplicacionDeBiblioteca.UI.Models.Libro>

@{
    ViewData["Title"] = "Lista De Libros";
}

<h1>Libros:</h1>

<p>
    <a asp-action="Create">Ingresar Libro</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaDePublicacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Autor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaDePublicacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

AplicacionDeBiblioteca.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aplicacion De Biblioteca</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Biblioteca</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="Listar">Lista de libros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="Create">Nuevo libro</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - UCR Informática Empresarial - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>